# a=10
# print(a)#NameError: name 'a' is not defined
# print(10+"10")#TypeError: unsupported operand type(s) for +: 'int' and 'str'
# print(1/0)#ZeroDivisionError: division by zero


# print("statement")
# print("statement")
# print("statement")
# print("statement")
# print("statement")
# print(1/0)# ZeroDivisionError: division by zero
# print("statement")
# print("statement")
# print("statement")
# print("statement")
# print("statement")


# try ..except block


# print("statement")
# print("statement")
# print("statement")
# print("statement")
# print("statement")
# try:
#     print(1/0)
# except:
#     print("error happend!!!")
# print("statement")
# print("statement")
# print("statement")
# print("statement")
# print("statement")


# print("statement")
# print("statement")
# print("statement")
# print("statement")
# print("statement")
# try:
#     #print(a)# nameerror
#     print(10 + "10")
#     #print(1/0)# zero division errro
# except NameError:
#     print("NameError happend!!!")
# except ZeroDivisionError:
#     print("ZeroDivisionError happend!!!")
# except Exception:
#     print("genereic exception")
# print("statement")
# print("statement")
# print("statement")
# print("statement")
# print("statement")



# print("statement")
# print("statement")
# print("statement")
# print("statement")
# print("statement")
# try:
#     #print(a)# nameerror
#     print(10 + "10")
#     #print(1/0)# zero division errro
# except Exception as var:
#     print("genereic exception happend !!!", var)
# print("statement")
# print("statement")
# print("statement")
# print("statement")
# print("statement")

# optional block ...else..finally

# print("statement")
# print("statement")
# print("statement")
# print("statement")
# print("statement")
# try:
#     #print(a)# nameerror
#     print("10" + "10")
#     #print(1/0)# zero division errro
# except Exception as var:
#     print("genereic exception happend !!!", var)
# else:# when there is no exception
#     print("no exception happened ...")
# finally:# execute with or without exception
#     print("finally block executed")
# print("statement")
# print("statement")
# print("statement")
# print("statement")
# print("statement")


